### ISSUE TITLE
client.filestorage.users.list(is_me=True) doesn't work

### ISSUE THREAD

**Issue by hwuiwon** [merge-api/merge-python-client#36]
This code will return an error below.

Code
```
from merge.client import Merge

client = Merge(api_key=MERGE_API_KEY, account_token=MY_ACCOUNT_TOKEN)

res = client.filestorage.users.list(is_me=True)

print(res)
```

Error
```bash
raise ApiError(status_code=_response.status_code, body=_response_json)
merge.core.api_error.ApiError: status_code: 400, body: {'non_field_errors': ['Provided filters are invalid.']}
```

I believe that this code should work or am I missing something here?

`mergepythonclient = "^0.2.2"`

**Comment by dsinghvi** [comment]
@hwuiwon thanks for reporting this issue. Looks like this has to do with the SDK and the server not being in sync with each other. I will get back to you with a fix this week!

**Comment by hwuiwon** [comment]
Great! I appreciate it.

**Comment by dsinghvi** [comment]
@hwuiwon this should now be fixed! I'm going to close this issue, but feel free to reopen if you encounter an issue!

**Comment by hwuiwon** [comment]
It works. Thanks for helping out.
