### ISSUE TITLE
Support for pydantic v2

### ISSUE THREAD

**Issue by entropi** [merge-api/merge-python-client#46]
As a library it's a bit challenging for the pydantic dependency to be pinned to v1.  Would it be possible to support both versions?

Here is one approach I see another library took in order to support both versions since all v1 functionality is still available in v2 (just under a different namespace): 

https://github.com/langchain-ai/langchain/blob/2c11302598ae81dc7a7d88388d0ea0fec7ba3b25/libs/langchain/langchain/pydantic_v1/main.py

**Comment by dsinghvi** [comment]
@entropi thanks for filing this issue and appreciate the link to langchani's approach. Will scope what it would take to support this!

**Comment by entropi** [comment]
Saw the merge on the fern repo @dsinghvi, thanks for the quick action!

**Comment by dsinghvi** [comment]
No problem! @rmkonnur should be releasing the SDK from the merge side soon!

**Comment by rmkonnur** [comment]
Thanks for the patience here! We rolled out **merge-python-client v0.2.7** which should support both v1 and v2. Feel free to reopen the issue if any further issues arise!
