### ISSUE TITLE
Asyncio support in README

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [merge-api/merge-python-client#85]
Hi, we're trying to integrate with merge API. I don't see any asyncio support which is a problem for event loop based programs. I noticed some httpx usage with AsyncClient. Any guidance would be helpful or an update to the README :)

**Comment by dsinghvi** [comment]
Hey @Andrew-Chen-Wang -- We'll update the README to include some `asyncio` examples. Apologize for the inconvenience.
